# Generated by Django 6.0.3 on 2026-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default='2026-04-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(default='09:00', max_length=5),
            preserve_default=False,
        ),
    ]
